project:
  type: website
  # execute-dir: project
  output-dir: docs

website:
  title: "Consumer Functional Trait Synthesis Group"
  favicon: images/hexasticker_mFD.png
  navbar:
    background: primary
    left:
      - text: "Code"
        href: about.qmd
      - text: "Data Agreement"
        href: data_agreement.qmd
      - text: "Authorship Agreement"
        href: auth_agreement.qmd
    right: 
      - icon: github
        href: https://github.com/lter/lter-sparc-consumer-fxn-diversity
      - text: NCEAS
        href: https://www.nceas.ucsb.edu/visiting-NCEAS
    page-footer: 
      # center:
      background: secondary
      
format:
  html:
    theme: 
      light: fnxlight.scss
      dark: fnxdark.scss
    mainfont: Open Sans
    # css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false

# editor: visual