project:
  type: website
  # execute-dir: project
  output-dir: docs

website:
  title: "Consumer Functional Trait Synthesis Group"
  favicon: images/hexasticker_mFD.png
  navbar:
    background: primary
    left:
      - text: "About"
        href: about.qmd
    right: 
      - icon: github
        href: https://github.com/mackwhite/aquatic-ecology-seminar
      - text: Ohio EPA
        href: https://epa.ohio.gov/divisions-and-offices/surface-water/reports-data/statewide-biological-and-water-quality-monitoring-and-assessment
    page-footer: 
      # center:
      background: secondary
      
format:
  html:
    theme: 
      light: fnxlight.scss
      dark: fnxdark.scss
    mainfont: Open Sans
    # css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false

# editor: visual