---
title: "Authorship Agreement"
editor: visual
---

**Project**: Temporal variation in taxonomic and functional diversity and nutrient cycling of consumers across aquatic ecosystems and LTER sites (Consumer Functional Diversity)

**Funding**: National Science Foundation Long Term Ecological Research Synthesis Grant

**Principal Investigators**: Dr. Shalanda Grier, Lauren Enright, Dr. Mack White, and Dr. Camille Magneville

**Database Managers:** Li Kui and Nick Lyon 

The following agreement has benefited greatly from and contains significant portions of formalized policies (i.e.,[ Nutrient Network](https://nutnet.org/), [Hurricane Ecosystem Response Synthesis Network](https://www.vims.edu/research/units/programs/hers_rcn/index.php), [Soil Data Harmonization & Synthesis](https://lter.github.io/som-website/index.html)), and synthesis resources (i.e., [Arctic Data Center](https://arcticdata.io/), [National Information Standards Organization)](https://www.niso.org/). Though each of these groups differ in their goals, each has worked hard and thought critically on how to ensure collaborative research, synthesis, and authorship is transparent. Further review of each organization's authorship agreements may be found on their respective websites. 

**Background:** It is well established that collaborative synthesis research elicits a deeper and more holistic understanding of our natural world. In this synthesis effort, we will use publicly available data, data published in peer-reviewed articles, and data from unpublished sources. Detailed metadata and a thorough understanding of each dataset will be necessary to link them across sites in a single database. As such, the cooperation and collaboration of scientists with intimate understandings of their respective datasets/sites will be critical to generating accurate research products. Furthermore, we believe that the working group will greatly benefit from the intellectual contributions of a team of scientists with diverse research backgrounds.

The primary purpose of this agreement is to ensure that the process of determining authorship for scholarly products derived from the working group is done consistently and transparently. The synthesis work involves collaborations and contributions primarily at two stages: 1) creating a synthesis database (Tier 2 data, see data agreement), and 2) the data analysis and drafting of the manuscript. The authorship lists at these two stages will be separated to distinguish between the primary contributions. 

**Authorship of the database used in the manuscript:** We anticipate this working group will publish three Tier 2 data packages. 1) consumer excretion rates X aggregated community data (aquatic sites), 2) trait data X aggregated community data (aquatic and terrestrial sites), and 3) satellite temperature data (aquatic sites). To document the process and acknowledge the contribution, authors for the data product will be invited to opt-in, and the invitation will be sent to the anyone who helped to harmonize and aggregate the raw data to cross-site dataset (Tier 1 data), or who developed the data structure for the aggregated dataset and help to concatenate site data (Tier 2 data). The people who contribute to the Tier 0 will be acknowledged in the data package and the link from the Tier 0 data will be cited as the data source for our final data package. 

**Authorship of the manuscript**: We look to the National Information Standards Organization (NISO) which has established a clear set of standards for authorship currently used by a number of scientific societies. Contributor Roles Taxonomy ([CRediT](https://credit.niso.org/), see list below) includes the roles typically associated with contributions to scholarly outputs. Given the nature of our synthesis efforts, roles will be used to aid in determining: 1) criteria for authorship and 2) authorship order to be evaluated by the primary author - if similar contributions exist, order will be determined by reverse alphabetical order. Individuals (regardless of their career stage or formal affiliation with the working group) who serve two or more of the following roles via their contributions will be solicited for opt-in authorship on resulting research products by the primary author via email with a deadline to accept or decline:

|                        |                     |                            |
|------------------------|---------------------|----------------------------|
| Conceptualization      | Resources           | Writing - original draft   |
| Data Curation          | Software            | Writing - review & editing |
| Formal Analysis        | Validation          | Supervision                |
| Methodology            | Visualization       | Investigation              |
| Project administration | Funding acquisition |                            |

**Criteria for accepting authorship:** Individuals accepting authorship should only do so if they are willing and able to commit the time necessary to be actively involved in the research process as outlined by the list above. We will use an opt-in model of authorship, where all authors approve the final version and document their contribution at the time of submission. The inclusive list of potential authors will be guided by early, often, and open discussion such that authorship for the manuscript is mostly determined before the first draft of any manuscript is complete and ready for review. This being said, substantial contributions (see CRediT roles above) at any point in the publication process (i.e., conceptualization to full acceptance by a peer-reviewed journal) will warrant an invitation for co-authorship. Author contributions should be documented and tracked in the “Contribution Spreadsheet” (located on the Working Group Google Drive) for transparency.  

**General guidelines for the primary author:** The primary author shall be very inclusive in soliciting potential co-authors for opt-in authorship. Primary authors will provide a draft of the manuscript to all co-authors and maintain frequent communication at each step in the review process, providing a final version of the manuscript to each of the co-authors once it has been submitted. At decision time, the primary author should forward the decision and reviews to all coauthors. As the working group begins wrapping up work and planning publications, the primary author will be responsible for facilitating communication with LNO Director Marty Downs so they can anticipate outreach opportunities and assist in communicating results to diverse audiences. 

This working group is expecting to publish at least 3 manuscripts. The co-PIs are working on establishing criteria for primary authorship and anchor author for each manuscript, based on the [CRediT](https://credit.niso.org/) criteria. This is an evolving discussion and the working group will be updated as a whole as the project progresses. 

**General guidelines for co-authors:** Each potential coauthor is expected to make substantial contributions to the manuscript. If you feel that someone should be added to the author list, send their contact information and rationale for inclusion to the primary author. Potential co-authors should acknowledge receipt of the draft manuscript and note whether they wish to be included as an author within a reasonable period set by the primary author (i.e., 2 weeks). If they do not respond in this time and after the primary author has made a reasonable effort to contact them (e.g. follow-up email and/or phone call), then they will be omitted as an author so that the manuscript can proceed. Co-authors that are interested in reviewing the manuscript should make this known along with a reasonable timeline for completing the review and returning any comments. All authors must provide feedback and revisions in a timely manner. If the manuscript has not been returned in the stated timeframe and after the primary author has made a reasonable effort to contact them (e.g. follow-up email and/or phone call), the primary author may decide to proceed without the feedback from the co-author.
